FROM citypulse-worker:develop-6f18a23-fix3
COPY simulation /app/simulation
COPY simulation_protocol /app/simulation_protocol
COPY scenario_catalog /app/scenario_catalog
COPY traffic_eval /app/traffic_eval
COPY traffic_llm_runtime /app/traffic_llm_runtime
COPY traffic_control /app/traffic_control
