"""Checkpoint contract v2: self-describing IPPO checkpoints and sidecars.

Contract v1 is the historical implicit metadata written by the v8 trainer.
Contract v2 adds canonical identity slots, an observation schema, the phase
feature count, normalization, collaboration-message schema and per-intersection
topology fingerprints.  v1 checkpoints must carry a sidecar generated by
``tools/migrate_checkpoint_contract.py``; a missing or tampered sidecar is a
hard error and is never silently repaired.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from .identity import IDENTITY_SLOT_IDS
from .model import PHASE_FEATURES

CHECKPOINT_CONTRACT_VERSION = 2

OBSERVATION_SCHEMA: dict[str, Any] = {
    "phase_one_hot": 8,
    "elapsed": 1,
    "identity_slots": len(IDENTITY_SLOT_IDS),
    "lane_features": [5, 20],
    "outgoing_summary": 3,
    "total": 8 + 1 + len(IDENTITY_SLOT_IDS) + 5 * 20 + 3,
}

NORMALIZATION: dict[str, str] = {
    "observation": "physical_fixed",
    "reward": "physical_fixed",
}

COLLAB_MESSAGE_SCHEMA: Any = None

CONTRACT_KEYS: tuple[str, ...] = (
    "checkpoint_contract_version",
    "identity_slots",
    "observation_schema",
    "phase_features",
    "normalization",
    "collab_message_schema",
    "model_version",
    "obs_dim",
    "act_dim",
    "action_interval",
    "max_green_factor",
    "phase_feature_schema",
    "effective_demand_enabled",
    "intersection_ids",
    "per_intersection_fingerprints",
)


def checkpoint_sha256(path: str | Path) -> str:
    """SHA-256 of a checkpoint file bytes."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sidecar_path(checkpoint_path: str | Path) -> Path:
    """Sidecar file for a v1 checkpoint: ``<checkpoint>.contract.json``."""
    return Path(checkpoint_path).with_suffix(
        Path(checkpoint_path).suffix + ".contract.json"
    )


def fingerprint_sha256(fingerprint: Mapping[str, Any]) -> str:
    """Deterministic SHA-256 (sorted keys, compact JSON) of a fingerprint."""
    canonical = json.dumps(
        fingerprint, sort_keys=True, ensure_ascii=True, separators=(",", ":")
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def intersection_fingerprint_from_index(index: Any) -> dict[str, Any]:
    """Extract topology facts from a StateBuilder ``_Idx`` object.

    ``index`` is duck-typed: it needs phase_order, n_phases, lane_order,
    outgoing_order, phase_connections, phase_movements, phase_durations,
    lane_capacities, lane_speed_limits, outgoing_capacities,
    flow_reference_rate.
    """
    return {
        "phase_order": [int(phase) for phase in index.phase_order],
        "n_phases": int(index.n_phases),
        "lane_order": [str(lane) for lane in index.lane_order],
        "outgoing_order": [str(lane) for lane in index.outgoing_order],
        "phase_connections": [
            [[str(a), str(b)] for a, b in sorted(pairs)]
            for pairs in index.phase_connections
        ],
        "phase_movements": [
            [[str(a), str(b)] for a, b in sorted(moves)]
            for moves in index.phase_movements
        ],
        "phase_durations": [round(float(value), 6) for value in index.phase_durations],
        "lane_capacities": {
            str(lane): round(float(cap), 6)
            for lane, cap in index.lane_capacities.items()
        },
        "lane_speed_limits": {
            str(lane): round(float(speed), 6)
            for lane, speed in index.lane_speed_limits.items()
        },
        "outgoing_capacities": {
            str(lane): round(float(cap), 6)
            for lane, cap in index.outgoing_capacities.items()
        },
        "flow_reference_rate": round(float(index.flow_reference_rate), 6),
    }


def build_sidecar(
    checkpoint_path: str | Path,
    *,
    checkpoint: Mapping[str, Any],
    fingerprints: Mapping[str, Mapping[str, Any]],
    created_by: str = "tools/migrate_checkpoint_contract.py",
) -> dict[str, Any]:
    """Build the v2 sidecar payload for a v1 checkpoint."""
    return {
        "checkpoint_contract_version": CHECKPOINT_CONTRACT_VERSION,
        "checkpoint_filename": Path(checkpoint_path).name,
        "sha256": checkpoint_sha256(checkpoint_path),
        "identity_slots": list(IDENTITY_SLOT_IDS),
        "observation_schema": dict(OBSERVATION_SCHEMA),
        "phase_features": int(PHASE_FEATURES),
        "normalization": dict(NORMALIZATION),
        "collab_message_schema": COLLAB_MESSAGE_SCHEMA,
        "model_version": str(checkpoint.get("model_version", "")),
        "obs_dim": int(checkpoint["obs_dim"]),
        "act_dim": int(checkpoint["act_dim"]),
        "action_interval": float(checkpoint["action_interval"]),
        "max_green_factor": float(checkpoint.get("max_green_factor", 2.0)),
        "phase_feature_schema": str(checkpoint.get("phase_feature_schema", "")),
        "effective_demand_enabled": bool(
            checkpoint.get("effective_demand_enabled", True)
        ),
        "reward_definition": checkpoint.get("reward_definition"),
        "training_periods": list(checkpoint.get("training_periods", ())),
        "training_seed_range": dict(checkpoint.get("training_seed_range", {})),
        "intersection_ids": [
            str(iid) for iid in checkpoint.get("intersection_ids", ())
        ],
        "per_intersection_fingerprints": {
            str(iid): {
                "sha256": fingerprint_sha256(fingerprint),
                "fingerprint": fingerprint,
            }
            for iid, fingerprint in fingerprints.items()
        },
        "created_by": created_by,
    }


def load_contract(
    checkpoint_path: str | Path,
    checkpoint: Mapping[str, Any],
) -> tuple[int, dict[str, Any]]:
    """Return ``(contract_version, contract_view)``.

    Inline v2 checkpoints are used directly.  v1 checkpoints require a sidecar;
    missing sidecar, SHA-256 mismatch, or wrong contract version is a hard error.
    """
    inline_version = checkpoint.get("checkpoint_contract_version")
    if inline_version is not None:
        if int(inline_version) != CHECKPOINT_CONTRACT_VERSION:
            raise ValueError(
                f"Unsupported checkpoint_contract_version={inline_version!r}; "
                f"expected {CHECKPOINT_CONTRACT_VERSION}"
            )
        missing = sorted(set(CONTRACT_KEYS) - set(checkpoint))
        if missing:
            raise ValueError(f"Inline contract v2 is incomplete: {missing}")
        return CHECKPOINT_CONTRACT_VERSION, dict(checkpoint)

    path = sidecar_path(checkpoint_path)
    if not path.is_file():
        raise ValueError(
            f"Checkpoint {Path(checkpoint_path).name} is contract v1 and has no "
            f"sidecar at {path.name}; run tools/migrate_checkpoint_contract.py "
            "and commit the sidecar. Silent metadata repair is forbidden."
        )
    sidecar = json.loads(path.read_text(encoding="utf-8"))
    if int(sidecar.get("checkpoint_contract_version", 0)) != CHECKPOINT_CONTRACT_VERSION:
        raise ValueError(f"Sidecar contract version mismatch: {path}")
    if str(sidecar.get("sha256", "")) != checkpoint_sha256(checkpoint_path):
        raise ValueError(
            f"Sidecar SHA-256 mismatch for {Path(checkpoint_path).name}"
        )
    return 1, sidecar


def validate_contract(
    contract_view: Mapping[str, Any],
    *,
    intersection_ids: Sequence[str],
    fingerprints: Mapping[str, Mapping[str, Any]],
    obs_dim: int,
    act_dim: int,
    action_interval: float,
    max_green_factor: float,
    phase_feature_schema: str,
    effective_demand_enabled: bool,
    model_version: str,
) -> None:
    """Validate a contract view against the live subset metadata."""
    if list(contract_view.get("identity_slots", ())) != list(IDENTITY_SLOT_IDS):
        raise ValueError(
            "Checkpoint identity slots do not match the canonical 20-slot table."
        )
    if contract_view.get("observation_schema") != OBSERVATION_SCHEMA:
        raise ValueError(
            "Checkpoint observation schema does not match the canonical v8 layout."
        )
    if int(contract_view.get("phase_features", -1)) != int(PHASE_FEATURES):
        raise ValueError("Checkpoint phase feature count does not match IPPO v8.")
    if contract_view.get("normalization") != NORMALIZATION:
        raise ValueError("Checkpoint normalization does not match physical_fixed.")
    if contract_view.get("collab_message_schema") is not None:
        raise ValueError(
            "Checkpoint declares a collaboration message schema but v8 uses none."
        )
    if str(contract_view.get("model_version", "")) != model_version:
        raise ValueError(
            f"Checkpoint model_version={contract_view.get(model_version)!r} "
            f"does not match {model_version!r}."
        )
    if int(contract_view.get("obs_dim", -1)) != obs_dim:
        raise ValueError("Checkpoint observation dimension does not match current metadata.")
    if int(contract_view.get("act_dim", -1)) != act_dim:
        raise ValueError("Checkpoint action dimension does not match current metadata.")
    if abs(float(contract_view["action_interval"]) - action_interval) > 1e-9:
        raise ValueError(
            "Checkpoint action interval does not match the current IPPO configuration."
        )
    if abs(float(contract_view.get("max_green_factor", -1.0)) - max_green_factor) > 1e-9:
        raise ValueError(
            "Checkpoint maximum-green configuration does not match current IPPO."
        )
    if contract_view.get("phase_feature_schema") != phase_feature_schema:
        raise ValueError("Checkpoint phase feature schema does not match current IPPO.")
    if bool(contract_view.get("effective_demand_enabled", True)) != bool(
        effective_demand_enabled
    ):
        raise ValueError("Checkpoint effective-demand flag does not match current IPPO.")

    saved_ids = tuple(str(iid) for iid in contract_view.get("intersection_ids", ()))
    current_ids = tuple(str(iid) for iid in intersection_ids)
    if not set(current_ids) <= set(saved_ids):
        raise ValueError(
            "Checkpoint was not trained on this intersection subset: "
            f"current={current_ids}, saved={saved_ids}"
        )
    stored = contract_view.get("per_intersection_fingerprints", {})
    for intersection_id in current_ids:
        entry = stored.get(intersection_id)
        if not isinstance(entry, Mapping):
            raise ValueError(
                f"Checkpoint contract has no fingerprint for {intersection_id}."
            )
        expected_hash = str(entry.get("sha256", ""))
        live_fingerprint = fingerprints.get(intersection_id)
        if live_fingerprint is None:
            raise ValueError(
                f"No live fingerprint available for {intersection_id}."
            )
        live_hash = fingerprint_sha256(live_fingerprint)
        if expected_hash != live_hash:
            raise ValueError(
                f"Intersection {intersection_id} topology fingerprint mismatch "
                f"(saved={expected_hash}, live={live_hash}); phase/lane/connection "
                "order or action-mask schema differs from training."
            )
