"""Checkpoint contract v2: self-describing IPPO checkpoints and sidecars.

Contract v1 is the historical implicit metadata written by the v8 trainer.
Contract v2 adds canonical identity slots, an observation schema, the phase
feature count, normalization, collaboration-message schema and per-intersection
topology fingerprints.  v1 checkpoints must carry a sidecar generated by
``tools/migrate_checkpoint_contract.py``; a missing or tampered sidecar is a
hard error and is never silently repaired.  Inline v2 checkpoints may use a
SHA-bound sidecar for an optional deployment compatibility profile; no other
inline contract field can be overridden there.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from .identity import IDENTITY_SLOT_IDS
from .model import PHASE_FEATURES

CHECKPOINT_CONTRACT_VERSION = 2
CANDIDATE_SCORING_PERIOD_PROFILE = "candidate_scoring_period_v1"

OBSERVATION_SCHEMA: dict[str, Any] = {
    "phase_one_hot": 8,
    "elapsed": 1,
    "identity_slots": len(IDENTITY_SLOT_IDS),
    "lane_features": [5, 20],
    "outgoing_summary": 3,
    "total": 8 + 1 + len(IDENTITY_SLOT_IDS) + 5 * 20 + 3,
}

NORMALIZATION: dict[str, str] = {
    "observation": "physical_fixed",
    "reward": "physical_fixed",
}

COLLAB_MESSAGE_SCHEMA: Any = None

CONTRACT_KEYS: tuple[str, ...] = (
    "checkpoint_contract_version",
    "identity_slots",
    "observation_schema",
    "phase_features",
    "normalization",
    "collab_message_schema",
    "model_version",
    "obs_dim",
    "act_dim",
    "action_interval",
    "max_green_factor",
    "phase_feature_schema",
    "effective_demand_enabled",
    "intersection_ids",
    "per_intersection_fingerprints",
)


def checkpoint_sha256(path: str | Path) -> str:
    """SHA-256 of a checkpoint file bytes."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sidecar_path(checkpoint_path: str | Path) -> Path:
    """Contract sidecar path: ``<checkpoint>.contract.json``."""
    return Path(checkpoint_path).with_suffix(
        Path(checkpoint_path).suffix + ".contract.json"
    )


def _load_sidecar_compatibility_profile(
    checkpoint_path: str | Path,
) -> str | None:
    """Load the sole sidecar extension allowed for an inline v2 checkpoint."""
    path = sidecar_path(checkpoint_path)
    if not path.is_file():
        return None
    sidecar = json.loads(path.read_text(encoding="utf-8"))
    profile = sidecar.get("topology_compatibility_profile")
    if profile is None:
        return None
    if (
        int(sidecar.get("checkpoint_contract_version", 0))
        != CHECKPOINT_CONTRACT_VERSION
    ):
        raise ValueError(f"Sidecar contract version mismatch: {path}")
    if str(sidecar.get("sha256", "")) != checkpoint_sha256(checkpoint_path):
        raise ValueError(
            f"Sidecar SHA-256 mismatch for {Path(checkpoint_path).name}"
        )
    return str(profile)


def fingerprint_sha256(fingerprint: Mapping[str, Any]) -> str:
    """Deterministic SHA-256 (sorted keys, compact JSON) of a fingerprint."""
    canonical = json.dumps(
        fingerprint, sort_keys=True, ensure_ascii=True, separators=(",", ":")
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _pair_union(groups: Any, *, field_name: str) -> list[list[str]]:
    """Return the canonical union of connection or movement pairs."""
    if not isinstance(groups, Sequence) or isinstance(groups, (str, bytes)):
        raise ValueError(f"Fingerprint {field_name} must be a sequence of phases.")
    pairs: set[tuple[str, str]] = set()
    for group in groups:
        if not isinstance(group, Sequence) or isinstance(group, (str, bytes)):
            raise ValueError(f"Fingerprint {field_name} contains an invalid phase.")
        for pair in group:
            if (
                not isinstance(pair, Sequence)
                or isinstance(pair, (str, bytes))
                or len(pair) != 2
            ):
                raise ValueError(f"Fingerprint {field_name} contains an invalid pair.")
            pairs.add((str(pair[0]), str(pair[1])))
    return [[first, second] for first, second in sorted(pairs)]


def _candidate_scoring_period_projection(
    fingerprint: Mapping[str, Any],
) -> dict[str, Any]:
    """Project a fingerprint onto facts that candidate scoring assumes invariant."""
    required = (
        "lane_order",
        "outgoing_order",
        "phase_connections",
        "phase_movements",
        "lane_capacities",
        "lane_speed_limits",
        "outgoing_capacities",
    )
    missing = [key for key in required if key not in fingerprint]
    if missing:
        raise ValueError(f"Fingerprint is missing period-invariant fields: {missing}")
    return {
        "lane_order": list(fingerprint["lane_order"]),
        "outgoing_order": list(fingerprint["outgoing_order"]),
        "connection_union": _pair_union(
            fingerprint["phase_connections"], field_name="phase_connections"
        ),
        "movement_union": _pair_union(
            fingerprint["phase_movements"], field_name="phase_movements"
        ),
        "lane_capacities": dict(fingerprint["lane_capacities"]),
        "lane_speed_limits": dict(fingerprint["lane_speed_limits"]),
        "outgoing_capacities": dict(fingerprint["outgoing_capacities"]),
    }


def _validate_candidate_scoring_period_fingerprint(
    fingerprint: Mapping[str, Any],
    *,
    act_dim: int,
    label: str,
) -> None:
    """Validate phase metadata before applying the opt-in period profile."""
    try:
        n_phases = int(fingerprint["n_phases"])
        phase_order = [int(phase) for phase in fingerprint["phase_order"]]
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"{label} fingerprint has invalid phase metadata.") from exc
    if not 1 <= n_phases <= act_dim:
        raise ValueError(
            f"{label} fingerprint n_phases={n_phases} exceeds checkpoint "
            f"act_dim={act_dim}."
        )
    if len(phase_order) != n_phases or len(set(phase_order)) != n_phases:
        raise ValueError(f"{label} fingerprint phase_order is inconsistent.")
    if any(
        phase < 0 or phase >= OBSERVATION_SCHEMA["phase_one_hot"]
        for phase in phase_order
    ):
        raise ValueError(f"{label} fingerprint phase_order exceeds observation slots.")
    for field_name in ("phase_connections", "phase_movements", "phase_durations"):
        values = fingerprint.get(field_name)
        if (
            not isinstance(values, Sequence)
            or isinstance(values, (str, bytes))
            or len(values) != n_phases
        ):
            raise ValueError(
                f"{label} fingerprint {field_name} does not match n_phases."
            )
    _candidate_scoring_period_projection(fingerprint)


def intersection_fingerprint_from_index(index: Any) -> dict[str, Any]:
    """Extract topology facts from a StateBuilder ``_Idx`` object.

    ``index`` is duck-typed: it needs phase_order, n_phases, lane_order,
    outgoing_order, phase_connections, phase_movements, phase_durations,
    lane_capacities, lane_speed_limits, outgoing_capacities,
    flow_reference_rate.
    """
    return {
        "phase_order": [int(phase) for phase in index.phase_order],
        "n_phases": int(index.n_phases),
        "lane_order": [str(lane) for lane in index.lane_order],
        "outgoing_order": [str(lane) for lane in index.outgoing_order],
        "phase_connections": [
            [[str(a), str(b)] for a, b in sorted(pairs)]
            for pairs in index.phase_connections
        ],
        "phase_movements": [
            [[str(a), str(b)] for a, b in sorted(moves)]
            for moves in index.phase_movements
        ],
        "phase_durations": [round(float(value), 6) for value in index.phase_durations],
        "lane_capacities": {
            str(lane): round(float(cap), 6)
            for lane, cap in index.lane_capacities.items()
        },
        "lane_speed_limits": {
            str(lane): round(float(speed), 6)
            for lane, speed in index.lane_speed_limits.items()
        },
        "outgoing_capacities": {
            str(lane): round(float(cap), 6)
            for lane, cap in index.outgoing_capacities.items()
        },
        "flow_reference_rate": round(float(index.flow_reference_rate), 6),
    }


def build_sidecar(
    checkpoint_path: str | Path,
    *,
    checkpoint: Mapping[str, Any],
    fingerprints: Mapping[str, Mapping[str, Any]],
    created_by: str = "tools/migrate_checkpoint_contract.py",
    topology_compatibility_profile: str | None = None,
) -> dict[str, Any]:
    """Build the v2 sidecar payload for a v1 checkpoint."""
    payload = {
        "checkpoint_contract_version": CHECKPOINT_CONTRACT_VERSION,
        "checkpoint_filename": Path(checkpoint_path).name,
        "sha256": checkpoint_sha256(checkpoint_path),
        "identity_slots": list(IDENTITY_SLOT_IDS),
        "observation_schema": dict(OBSERVATION_SCHEMA),
        "phase_features": int(PHASE_FEATURES),
        "normalization": dict(NORMALIZATION),
        "collab_message_schema": COLLAB_MESSAGE_SCHEMA,
        "model_version": str(checkpoint.get("model_version", "")),
        "obs_dim": int(checkpoint["obs_dim"]),
        "act_dim": int(checkpoint["act_dim"]),
        "action_interval": float(checkpoint["action_interval"]),
        "max_green_factor": float(checkpoint.get("max_green_factor", 2.0)),
        "phase_feature_schema": str(checkpoint.get("phase_feature_schema", "")),
        "effective_demand_enabled": bool(
            checkpoint.get("effective_demand_enabled", True)
        ),
        "reward_definition": checkpoint.get("reward_definition"),
        "training_periods": list(checkpoint.get("training_periods", ())),
        "training_seed_range": dict(checkpoint.get("training_seed_range", {})),
        "intersection_ids": [
            str(iid) for iid in checkpoint.get("intersection_ids", ())
        ],
        "per_intersection_fingerprints": {
            str(iid): {
                "sha256": fingerprint_sha256(fingerprint),
                "fingerprint": fingerprint,
            }
            for iid, fingerprint in fingerprints.items()
        },
        "created_by": created_by,
    }
    if topology_compatibility_profile is not None:
        payload["topology_compatibility_profile"] = str(
            topology_compatibility_profile
        )
    return payload


def load_contract(
    checkpoint_path: str | Path,
    checkpoint: Mapping[str, Any],
) -> tuple[int, dict[str, Any]]:
    """Return ``(contract_version, contract_view)``.

    Inline v2 checkpoints use their embedded contract plus, when present, the
    SHA-bound sidecar compatibility profile.  v1 checkpoints require a sidecar;
    missing sidecar, SHA-256 mismatch, or wrong contract version is a hard error.
    """
    inline_version = checkpoint.get("checkpoint_contract_version")
    if inline_version is not None:
        if int(inline_version) != CHECKPOINT_CONTRACT_VERSION:
            raise ValueError(
                f"Unsupported checkpoint_contract_version={inline_version!r}; "
                f"expected {CHECKPOINT_CONTRACT_VERSION}"
            )
        missing = sorted(set(CONTRACT_KEYS) - set(checkpoint))
        if missing:
            raise ValueError(f"Inline contract v2 is incomplete: {missing}")
        contract_view = dict(checkpoint)
        if "topology_compatibility_profile" not in contract_view:
            profile = _load_sidecar_compatibility_profile(checkpoint_path)
            if profile is not None:
                contract_view["topology_compatibility_profile"] = profile
        return CHECKPOINT_CONTRACT_VERSION, contract_view

    path = sidecar_path(checkpoint_path)
    if not path.is_file():
        raise ValueError(
            f"Checkpoint {Path(checkpoint_path).name} is contract v1 and has no "
            f"sidecar at {path.name}; run tools/migrate_checkpoint_contract.py "
            "and commit the sidecar. Silent metadata repair is forbidden."
        )
    sidecar = json.loads(path.read_text(encoding="utf-8"))
    if int(sidecar.get("checkpoint_contract_version", 0)) != CHECKPOINT_CONTRACT_VERSION:
        raise ValueError(f"Sidecar contract version mismatch: {path}")
    if str(sidecar.get("sha256", "")) != checkpoint_sha256(checkpoint_path):
        raise ValueError(
            f"Sidecar SHA-256 mismatch for {Path(checkpoint_path).name}"
        )
    return 1, sidecar


def validate_contract(
    contract_view: Mapping[str, Any],
    *,
    intersection_ids: Sequence[str],
    fingerprints: Mapping[str, Mapping[str, Any]],
    obs_dim: int,
    act_dim: int,
    action_interval: float,
    max_green_factor: float,
    phase_feature_schema: str,
    effective_demand_enabled: bool,
    model_version: str,
) -> None:
    """Validate a contract view against the live subset metadata."""
    compatibility_profile = contract_view.get("topology_compatibility_profile")
    if compatibility_profile not in (None, CANDIDATE_SCORING_PERIOD_PROFILE):
        raise ValueError(
            "Unsupported topology_compatibility_profile="
            f"{compatibility_profile!r}."
        )
    if list(contract_view.get("identity_slots", ())) != list(IDENTITY_SLOT_IDS):
        raise ValueError(
            "Checkpoint identity slots do not match the canonical 20-slot table."
        )
    if contract_view.get("observation_schema") != OBSERVATION_SCHEMA:
        raise ValueError(
            "Checkpoint observation schema does not match the canonical v8 layout."
        )
    if int(contract_view.get("phase_features", -1)) != int(PHASE_FEATURES):
        raise ValueError("Checkpoint phase feature count does not match IPPO v8.")
    if contract_view.get("normalization") != NORMALIZATION:
        raise ValueError("Checkpoint normalization does not match physical_fixed.")
    if contract_view.get("collab_message_schema") is not None:
        raise ValueError(
            "Checkpoint declares a collaboration message schema but v8 uses none."
        )
    if str(contract_view.get("model_version", "")) != model_version:
        raise ValueError(
            f"Checkpoint model_version={contract_view.get(model_version)!r} "
            f"does not match {model_version!r}."
        )
    if int(contract_view.get("obs_dim", -1)) != obs_dim:
        raise ValueError("Checkpoint observation dimension does not match current metadata.")
    if int(contract_view.get("act_dim", -1)) != act_dim:
        raise ValueError("Checkpoint action dimension does not match current metadata.")
    if abs(float(contract_view["action_interval"]) - action_interval) > 1e-9:
        raise ValueError(
            "Checkpoint action interval does not match the current IPPO configuration."
        )
    if abs(float(contract_view.get("max_green_factor", -1.0)) - max_green_factor) > 1e-9:
        raise ValueError(
            "Checkpoint maximum-green configuration does not match current IPPO."
        )
    if contract_view.get("phase_feature_schema") != phase_feature_schema:
        raise ValueError("Checkpoint phase feature schema does not match current IPPO.")
    if bool(contract_view.get("effective_demand_enabled", True)) != bool(
        effective_demand_enabled
    ):
        raise ValueError("Checkpoint effective-demand flag does not match current IPPO.")

    saved_ids = tuple(str(iid) for iid in contract_view.get("intersection_ids", ()))
    current_ids = tuple(str(iid) for iid in intersection_ids)
    if not set(current_ids) <= set(saved_ids):
        raise ValueError(
            "Checkpoint was not trained on this intersection subset: "
            f"current={current_ids}, saved={saved_ids}"
        )
    stored = contract_view.get("per_intersection_fingerprints", {})
    for intersection_id in current_ids:
        entry = stored.get(intersection_id)
        if not isinstance(entry, Mapping):
            raise ValueError(
                f"Checkpoint contract has no fingerprint for {intersection_id}."
            )
        expected_hash = str(entry.get("sha256", ""))
        live_fingerprint = fingerprints.get(intersection_id)
        if live_fingerprint is None:
            raise ValueError(
                f"No live fingerprint available for {intersection_id}."
            )
        live_hash = fingerprint_sha256(live_fingerprint)
        if expected_hash != live_hash:
            if compatibility_profile != CANDIDATE_SCORING_PERIOD_PROFILE:
                raise ValueError(
                    f"Intersection {intersection_id} topology fingerprint mismatch "
                    f"(saved={expected_hash}, live={live_hash}); phase/lane/connection "
                    "order or action-mask schema differs from training."
                )
            saved_fingerprint = entry.get("fingerprint")
            if not isinstance(saved_fingerprint, Mapping):
                raise ValueError(
                    "Checkpoint contract has no stored fingerprint for "
                    f"{intersection_id}."
                )
            if fingerprint_sha256(saved_fingerprint) != expected_hash:
                raise ValueError(
                    "Checkpoint stored fingerprint hash mismatch for "
                    f"{intersection_id}."
                )
            _validate_candidate_scoring_period_fingerprint(
                saved_fingerprint, act_dim=act_dim, label="Saved"
            )
            _validate_candidate_scoring_period_fingerprint(
                live_fingerprint, act_dim=act_dim, label="Live"
            )
            if _candidate_scoring_period_projection(
                saved_fingerprint
            ) != _candidate_scoring_period_projection(live_fingerprint):
                raise ValueError(
                    f"Intersection {intersection_id} topology fingerprint mismatch "
                    "outside the candidate-scoring period compatibility profile."
                )
